include=-I/Users/cheng109/toberemoved/phosim/phosim_core/source/cfitsio/include
lib=-L/Users/cheng109/toberemoved/phosim/phosim_core/source/cfitsio/lib
all:
	g++ -lcfitsio $(include) $(lib)  commons.cpp main.cpp Image.cpp -o junGL
	./junGL
